# Generated by Django 2.2 on 2019-05-05 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.URLField(help_text="It should start with a 'http://' and contain no spaces.", verbose_name='Web Reference')),
            ],
            options={
                'verbose_name': 'URL',
            },
        ),
        migrations.CreateModel(
            name='LegendCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name_pt', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('description_pt', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('description_en', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='legendcategory_creator', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='legendcategory_modifier', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_categories', to='legends.LegendCategory', verbose_name='Is a sub-category of')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
