# Generated by Django 2.2 on 2019-05-06 22:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0003_auto_20190506_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='narrative',
            options={'ordering': ('title',), 'verbose_name': 'Narrative'},
        ),
        migrations.AlterField(
            model_name='narrative',
            name='transcription',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Transcription'),
        ),
        migrations.AlterField(
            model_name='narrative',
            name='year_narrative',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
