# Generated by Django 2.2 on 2019-05-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0004_auto_20190506_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narrative',
            name='slug',
        ),
        migrations.AddField(
            model_name='narrative',
            name='slug_en',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='narrative',
            name='slug_pt',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
    ]
