# Generated by Django 2.2 on 2019-05-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0006_auto_20190510_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='narrativeversion',
            options={'verbose_name': 'Related Narrative', 'verbose_name_plural': 'Related Narratives'},
        ),
    ]
