# Generated by Django 2.2 on 2019-05-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0007_auto_20190510_2236'),
    ]

    operations = [
        migrations.RenameModel('LegendCategory', 'Category'),
    ]
