# Generated by Django 2.2 on 2019-05-11 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0008_rename_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=53, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_pt',
            field=models.SlugField(blank=True, max_length=53, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='category_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='modifier',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='category_modifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
