# Generated by Django 2.2 on 2019-05-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0010_auto_20190512_2052'),
    ]

    operations = [
        migrations.RunSQL('INSERT INTO legends_narrative_motifs (narrative_id,  motif_id) (SELECT narrative_id, motif_id FROM legends_narrativemotif)'),
    ]
