# Generated by Django 2.2 on 2019-05-12 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0011_copy_narativemotifs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NarrativeMotif',
        ),
    ]
