# Generated by Django 2.2 on 2019-12-08 19:58

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0012_delete_narrativemotif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='narrative',
            options={'ordering': [django.db.models.functions.text.Lower('title')], 'verbose_name': 'Narrative'},
        ),
    ]
