# Generated by Django 2.2 on 2019-04-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motif', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Index', 'verbose_name_plural': 'Indices'},
        ),
        migrations.RenameField(
            model_name='index',
            old_name='modified',
            new_name='modifier',
        ),
        migrations.RenameField(
            model_name='motif',
            old_name='modified',
            new_name='modifier',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='modified',
            new_name='modifier',
        ),
    ]
