# Generated by Django 2.2 on 2019-04-15 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motif', '0002_auto_20190415_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='type',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='type',
            name='modifier',
        ),
    ]
