# Generated by Django 2.2 on 2019-05-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motif', '0003_auto_20190415_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motif',
            old_name='descriptor',
            new_name='descriptor_en',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='descriptor',
            new_name='descriptor_en',
        ),
        migrations.AddField(
            model_name='motif',
            name='descriptor_pt',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='type',
            name='descriptor_pt',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
