# Generated by Django 2.2 on 2019-04-15 22:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concelho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dico', models.CharField(blank=True, max_length=4, verbose_name='DiCo')),
                ('nome', models.CharField(max_length=50, verbose_name='Name')),
                ('area', models.FloatField(null=True, verbose_name='Area')),
                ('nuts', models.IntegerField(blank=True, null=True, verbose_name='NUT CODE')),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('di', models.CharField(max_length=2, verbose_name='Di')),
                ('nome', models.CharField(max_length=50, verbose_name='Name')),
                ('area', models.FloatField(null=True, verbose_name='Area')),
            ],
            options={
                'verbose_name': 'District',
            },
        ),
        migrations.CreateModel(
            name='NUTSII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'NUTS II',
            },
        ),
        migrations.CreateModel(
            name='NUTSIII',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(blank=True, max_length=2)),
                ('nutsii', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portugal.NUTSII')),
            ],
            options={
                'verbose_name': 'NUTS III',
            },
        ),
        migrations.CreateModel(
            name='Freguesia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dico', models.CharField(max_length=4, verbose_name='DiCo')),
                ('dicofre', models.CharField(max_length=6, verbose_name='DiCoPar')),
                ('freguesia', models.CharField(max_length=100, verbose_name='Parish')),
                ('outras_inf', models.CharField(blank=True, max_length=255, verbose_name='Other Info.')),
                ('area2008_1', models.FloatField(null=True, verbose_name='Area')),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('concelho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portugal.Concelho', verbose_name='County')),
            ],
            options={
                'verbose_name': 'County/Parish',
                'verbose_name_plural': 'Counties and Parishes',
                'ordering': ['freguesia'],
            },
        ),
        migrations.AddField(
            model_name='concelho',
            name='distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portugal.Distrito', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='concelho',
            name='nutsiii',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portugal.NUTSIII', verbose_name='NUTS III'),
        ),
    ]
