# Generated by Django 2.2 on 2019-12-08 16:58

from django.db import migrations, models
from django.core.serializers import deserialize
import django.db.models.deletion

nutsmap = {}  # map old nuts3 to new nuts2
concelho_nutsiii = {}


def copy_nuts(apps, schema_editor):
    global concelho_nutsiii, nutsmap
    nuts3 = apps.get_model("portugal", "NUTSIII")
    nuts2 = apps.get_model("portugal", "NUTSII")
    concelho = apps.get_model("portugal", "Concelho")
    with open('portugal/fixtures/nutsiii.json') as fixture:
        nutsiii = deserialize('json', fixture)
        for ni in nutsiii:
            n3 = ni.object
            parent = nuts2.objects.get(pk=n3.nutsii_id)
            n2 = nuts2(designacao=n3.designacao, code=n3.code, parent=parent, lft=parent.lft+1,
                       tree_id=parent.tree_id, rght=parent.rght+1, level=1)
            n2.save()
            nutsmap[str(n3.pk)] = n2.pk
    concelho_nutsiii = dict([(str(a), b) for a, b in concelho.objects.values_list('pk', 'nutsiii_id') if b])
    concelho.objects.all().update(nutsiii=None)


def restore_nuts(apps, schema_editor):

    global concelho_nutsiii, nutsmap
    concelho = apps.get_model("portugal", "Concelho")
    for k in concelho_nutsiii.keys():
        concelho_nutsiii[k] = nutsmap[str(concelho_nutsiii[k])]
    for old, nu in concelho_nutsiii.items():
        x = concelho.objects.get(pk=int(old))
        x.nutsiii_id = nu
        x.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portugal', '0002_auto_20191208_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concelho',
            name='nutsiii',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portugal.NUTSIII', verbose_name='NUTS III'),
        ),
        migrations.RunPython(copy_nuts),
        migrations.AlterModelOptions(
            name='nutsii',
            options={'verbose_name_plural': 'NUTS'},
        ),
        migrations.AlterField(
            model_name='concelho',
            name='nutsiii',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portugal.NUTSII', verbose_name='NUTS III'),
        ),
        migrations.RunPython(restore_nuts),
    ]
    # NOTE: Must run NUTS.objects.rebuild() after this
