# Generated by Django 2.2 on 2019-12-09 00:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portugal', '0006_auto_20191208_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freguesia',
            name='dico',
        ),
        migrations.AddField(
            model_name='freguesia',
            name='nuts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portugal.NUTS', verbose_name='NUTS'),
        ),
        migrations.AddField(
            model_name='freguesia',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='portugal.Freguesia'),
        ),
        migrations.AlterField(
            model_name='freguesia',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='freguesia',
            name='concelho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portugal.Concelho', verbose_name='County'),
        ),
    ]
