# Generated by Django 2.2 on 2019-12-08 22:43

from django.db import migrations


def copy_missing_concelhos(apps, schema_editor):
    concelho = apps.get_model("portugal", "Concelho")
    freguesia = apps.get_model("portugal", "Freguesia")
    freg_dicos = freguesia.objects.filter(name='-').values_list('dico', flat=True)
    conc_dicos = concelho.objects.values_list('dico', flat=True)
    outliars = set(conc_dicos) - set(freg_dicos)
    concelhos = concelho.objects.filter(dico__in=outliars)
    for conc in concelhos:
        freg = freguesia(name='-', concelho_id=conc.pk, mpoly=conc.mpoly, dicofre=conc.dico+'00',
                         area=conc.area, level=2, lft=1, rght=2, tree_id=1)
        freg.save()


def copy_distritos(apps, schema_editor):
    distrito = apps.get_model("portugal", "Distrito")
    freguesia = apps.get_model("portugal", "Freguesia")
    for dist in distrito.objects.all():
        reg = freguesia(name='-', dicofre=dist.di+"0000", area=dist.area, level=1, lft=1, rght=2, tree_id=1)
        reg.save()


def copy_nuts(apps, schema_editor):
    concelho = apps.get_model("portugal", "Concelho")
    freguesia = apps.get_model("portugal", "Freguesia")
    for c in concelho.objects.filter(nutsiii__isnull=False):
        try:
            f = freguesia.objects.get(dicofre=c.dico+"00")
        except freguesia.MultipleObjectsReturned:
            print(c.dico)
        else:
            f.nuts = c.nutsiii
            f.save()


def setup_tree(apps, schema_editor):
    freguesia = apps.get_model("portugal", "Freguesia")
    distritos = freguesia.objects.filter(dicofre__endswith="0000")
    for d in distritos:
        for c in freguesia.objects.filter(dicofre__startswith=d.dicofre[:2], dicofre__endswith="00").exclude(pk=d.pk):
            for f in freguesia.objects.exclude(name='-').filter(dicofre__startswith=c.dicofre[:4]):
                f.parent = c
                f.level = 3
                f.save()
            c.parent = d
            c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portugal', '0007_auto_20191209_0009'),
    ]

    operations = [
        migrations.RunPython(copy_missing_concelhos),
        migrations.RunPython(copy_distritos),
        migrations.RunPython(copy_nuts),
        migrations.RunPython(setup_tree),

    ]
    # NOTE: requires rebuild()
