# Generated by Django 2.2 on 2019-12-09 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portugal', '0008_auto_20191209_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freguesia',
            name='concelho',
        ),
    ]
