# Generated by Django 2.2 on 2019-12-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portugal', '0009_remove_freguesia_concelho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freguesia',
            options={'ordering': ['lft'], 'verbose_name': 'County/Parish', 'verbose_name_plural': 'Counties and Parishes'},
        ),
    ]
