# Generated by Django 2.2 on 2019-12-15 20:37

from django.db import migrations


def copy_missing_names(apps, schema_editor):
    ConcelhoModel = apps.get_model("portugal", "Concelho")
    FreguesiaModel = apps.get_model("portugal", "Freguesia")
    DistritoModel = apps.get_model("portugal", "Distrito")
    freguesias = FreguesiaModel.objects.filter(dicofre__endswith='00').exclude(dicofre__endswith='0000')
    for freg in freguesias:
        conc = ConcelhoModel.objects.get(dico=freg.dicofre[:4])
        freg.name = conc.name
        freg.save()
    freguesias = FreguesiaModel.objects.filter(dicofre__endswith='0000')
    for freg in freguesias:
        distrito = DistritoModel.objects.get(di=freg.dicofre[:2])
        freg.name = distrito.name
        freg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portugal', '0010_auto_20191215_2037'),
    ]

    operations = [
        migrations.RunPython(copy_missing_names)
    ]
