# Generated by Django 2.2 on 2019-12-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portugal', '0011_auto_20191215_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Concelho',
        ),
        migrations.DeleteModel(
            name='Distrito',
        ),
    ]
