# Generated by Django 2.2 on 2019-12-15 22:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0013_auto_20191208_1958'),
        ('portugal', '0012_auto_20191215_2156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Freguesia',
            new_name='Region',
        )
    ]
