# Generated by Django 2.2 on 2019-05-02 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150, verbose_name='Country')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('-', 'Unknown/Undeclared')], max_length=1, null=True)),
                ('birth_year', models.SmallIntegerField(blank=True, max_length='4', null=True, verbose_name='Year of Birth')),
            ],
            options={
                'verbose_name': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='VolumeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('medium', models.CharField(choices=[('print', 'Print'), ('audio', 'Audio'), ('video', 'Video')], default='print', max_length=5, verbose_name='Medium type')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Sub-Title')),
                ('type', models.CharField(blank=True, choices=[('BOOK', 'Book'), ('COLLECTION', 'Collection'), ('MAGAZINE', 'Magazine'), ('JOURNAL', 'Journal'), ('NEWSPAPER', 'Newspaper'), ('ARTICLE', 'Article')], default='BOOK', max_length=15, verbose_name='Volume Type')),
                ('editor', models.CharField(blank=True, max_length=255, verbose_name='Editor')),
                ('pub_year', models.CharField(blank=True, help_text='Year of publication', max_length=4, verbose_name='Year')),
                ('original_year', models.CharField(blank=True, help_text='Year of publication of original print', max_length=4, null=True, verbose_name='Original Year')),
                ('is_collection', models.BooleanField(default=False, editable=False, verbose_name='Is Multiple')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('book_url', models.URLField(blank=True, null=True, verbose_name='Book/Author web address')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('presentation', models.CharField(blank=True, max_length=10, verbose_name='Presentation')),
                ('slug', models.SlugField(max_length=255)),
                ('authors', models.ManyToManyField(related_name='book_authors', to='biblio.Person', verbose_name='Authors')),
                ('belongs_to', models.ForeignKey(blank=True, limit_choices_to={'is_collection': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='biblio.Volume', verbose_name='In')),
                ('city', models.ForeignKey(blank=True, max_length=150, on_delete=django.db.models.deletion.PROTECT, to='biblio.City', verbose_name='City')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblio.Publisher', verbose_name='Publisher')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Part, chaper, passage, page, etc..', max_length=255, verbose_name='Excerpt')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblio.Volume', verbose_name='Volume')),
            ],
        ),
    ]
