# Generated by Django 2.2 on 2019-05-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='name_pt',
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Year of Birth'),
        ),
    ]
