# Generated by Django 2.2 on 2019-05-07 21:27

import apl.models
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_pt', models.CharField(blank=True, max_length=128, verbose_name='title')),
                ('title_en', models.CharField(blank=True, max_length=128, verbose_name='title')),
                ('short_title_pt', models.CharField(blank=True, help_text='On the menus. Defaults to max of 3 words', max_length=50, verbose_name='short title')),
                ('short_title_en', models.CharField(blank=True, help_text='On the menus. Defaults to max of 3 words', max_length=50, verbose_name='short title')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('keywords_pt', tagging.fields.TagField(blank=True, max_length=255, verbose_name='keywords')),
                ('keywords_en', tagging.fields.TagField(blank=True, max_length=255, verbose_name='keywords')),
                ('slug_pt', models.CharField(blank=True, db_index=True, editable=False, max_length=192)),
                ('slug_en', models.CharField(blank=True, db_index=True, editable=False, max_length=192)),
                ('menu', models.CharField(blank=True, choices=[('top', 'Top'), ('bottom', 'Bottom')], max_length=1, verbose_name='Menu')),
                ('is_public', models.BooleanField(default=True, help_text='public articles will be made visible on the website', verbose_name='publish')),
                ('date_pub', models.DateField(blank=True, verbose_name='publication date')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='content.Article', verbose_name='Ancestor')),
            ],
            options={
                'verbose_name': 'Content',
            },
            bases=(apl.models.SlugifyMixin, models.Model),
        ),
    ]
