# Generated by Django 2.2 on 2019-05-07 21:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='text'),
        ),
    ]
