# Generated by Django 2.2 on 2019-05-07 22:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20190507_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='text_en',
        ),
        migrations.AddField(
            model_name='article',
            name='text_pt',
            field=tinymce.models.HTMLField(blank=True, verbose_name='text'),
        ),
    ]
