# Generated by Django 2.2 on 2019-05-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20190507_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_pub',
            field=models.DateField(auto_created=True, blank=True, verbose_name='publication date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug_en',
            field=models.CharField(blank=True, db_index=True, max_length=192),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug_pt',
            field=models.CharField(blank=True, db_index=True, max_length=192),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_pt',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
    ]
